# Workflow to deploy documentation, test reports, and playgrounds to GitHub Pages
#
name: Deploy Docs, Test Reports, and Playgrounds

on:
  push:
    branches: [main]
    paths:
      - package.json
      - package-lock.json
      - 'docs/**'
      - 'apps/playground-2d/**'
      - 'apps/playground-3d/**'
      - 'packages/**'

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Not needed if lastUpdated is not enabled
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm # or pnpm / yarn
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Install dependencies
        run: npm ci
      # Build all packages
      - name: Build
        run: npx nx run-many --target=build --all
      # Run tests and generate reports with Vitest
      - name: Run Vitest to generate test reports
        run: npm run test:report
      # Build documentation with VitePress
      - name: Build with VitePress
        run: npm run docs:build
      # Build 2D playground with Nx and Vite
      - name: Build 2D playground
        run: ./node_modules/.bin/nx build @fibbojs/playground-2d
      # Build 3D playground with Nx and Vite
      - name: Build 3D playground
        run: ./node_modules/.bin/nx build @fibbojs/playground-3d
      # Move test reports to the docs folder
      - name: Move test reports to the docs folder
        run: mv html docs/.vitepress/dist/test-reports && mv coverage docs/.vitepress/dist/coverage
      # Move playgrounds to the docs folder
      - name: Move playgrounds to the docs folder
        run: mv apps/playground-2d/dist docs/.vitepress/dist/playground-2d && mv apps/playground-3d/dist docs/.vitepress/dist/playground-3d
      # Upload artifacts
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/.vitepress/dist

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
