# Workflow to publish a new release to NPM
#
name: Publish to NPM

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # Needed for provenance data generation
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - name: Test package
        run: npm run test
      - name: Build
        run: npm run build
      # Configure Git for automated commits
      - name: Configuring Git
        run: git config --global user.name "GitHub CD bot" && git config --global user.email "github-cd-bot@users.noreply.github.com"
      # Publish package to NPM
      - name: Publish package to NPM
        run: nx release version ${{ github.event.release.tag_name }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
      # Push changes to GitHub (updated package.json,...)
      - name: Push changes to GitHub
        run: git commit -am "Release ${{ github.event.release.tag_name }}" && git push origin HEAD:main
