# Workflow to run the tests on every push or pull request
#
name: Run Tests

on:
  push:
    branches:
      - main
    paths:
      - package.json
      - package-lock.json
      - 'src/**'
      - 'test/**'
  pull_request:
    branches:
      - main
    paths:
      - package.json
      - package-lock.json
      - 'src/**'
      - 'test/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - name: Test all packages
        run: npx nx run-many --target=test --all
