name: Run Tests

on:
  push:
    branches:
      - main
    paths:
      - 'package.json'
      - 'package-lock.json'
      - 'src/**'
      - 'test/**'
  pull_request:
    branches:
      - main
    paths:
      - 'package.json'
      - 'package-lock.json'
      - 'src/**'
      - 'test/**'

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: 18
            registry-url: https://registry.npmjs.org/
        - run: npm ci
        - name: Test package
          run: npm run test
